#ifndef __INCLUDE_ORA_ERROR_H__INCLUDED__
#define __INCLUDE_ORA_ERROR_H__INCLUDED__

#define DB_CLOSED                      (-3114)
#define OERR_ORA_NOT_LOGGED_IN          -3114
#define OERR_ORA_VALUE_CANNOT_BE_NULL   -1400
#define OERR_ORA_NO_ROWS_FOUND          -1403
#define OERR_ORA_FETCHED_COLUMN_NULL    -1405
#define OERR_ORACLE_SUCCESS               0
#define OERR_ANSI_NO_ROWS_FOUND          100
#define OERR_ORA_MULTIPLE_ROWS          -1422
#define OERR_ORA_DUPLICATE_INSERT       -1
#define OERR_ORA_FETCH_OUT_OF_SEQ       -1002
#define OERR_ORA_RET_TOO_MANY_ROWS      -2112
#define OERR_ORA_INSUFF_PRIVS           -1031
#define OERR_ORA_NOT_LOGGED_IN2		    -1012
#define OERR_ORA_NO_TNS_LISTENER        -12541
#define OERR_ORA_LITERAL_DATE_MISMATCH  -1861
#define OERR_ORA_TABLE_NOT_FOUND        -942
#define OERR_ORA_TNS_LISTENER_SID_FIND_FAILURE -12505
#endif // __INCLUDE_ORA_ERROR_H__INCLUDED__

